In [2]:
import numpy as np

In [89]:
def softmax(x):
    orig_shape = x.shape
    
    if len(x.shape) > 1:
        x -= np.max(x, axis=1).reshape(-1,1)
        x = np.exp(x)
        x /= np.sum(x, axis=1).reshape(-1,1)
    else: 
        x -= np.max(x)
        x = np.exp(x)
        x /= np.sum(x)
        
    assert x.shape == orig_shape
    return x

In [98]:
def test_softmax_basic():
    print "Running basic tests..."
    test1 = softmax(np.array([1,2]))
    print test1
    ans1 = np.array([0.26894142,  0.73105858])
    assert np.allclose(test1, ans1, rtol=1e-05, atol=1e-06)
    
    test2 = softmax(np.array([[1001,1002],[3,4]]))
    print test2
    ans2 = np.array([
        [0.26894142, 0.73105858],
        [0.26894142, 0.73105858]])
    assert np.allclose(test2, ans2, rtol=1e-05, atol=1e-06)
    
    test3 = softmax(np.array([
        [-1001,-1002]]))
    print test3
    ans3 = np.array([0.73105858, 0.26894142])
    assert np.allclose(test3, ans3, rtol=1e-05, atol=1e-06)
    
    print "You should be able to verify these results by hand!\n"

In [99]:
%%time
test_softmax_basic()

Running basic tests...
[ 0.26894142  0.73105858]
[[ 0.26894142  0.73105858]
 [ 0.26894142  0.73105858]]
[[ 0.73105858  0.26894142]]
You should be able to verify these results by hand!

CPU times: user 3.19 ms, sys: 1.19 ms, total: 4.38 ms
Wall time: 3.42 ms


In [48]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]]);

In [49]:
print 'a', a.shape
print a
print ''
print 'a\'', a.transpose().shape
print a.transpose()

print ''

print 'b', b.shape
print b
print ''
print 'b\'', b.transpose().shape
print b.transpose()


a (3, 2)
[[1 2]
 [3 4]
 [5 6]]

a' (2, 3)
[[1 3 5]
 [2 4 6]]

b (2, 3)
[[1 2 3]
 [4 5 6]]

b' (3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [54]:
a * b.transpose()

array([[ 1,  8],
       [ 6, 20],
       [15, 36]])

In [73]:
a = np.array([[1,2,3,4,5]]).transpose()
b = np.array([[1,2,3,4,5]]).transpose()

print a
print b

print  a.transpose() * b

[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [79]:
br = np.eye(5)
br

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])